### ISSUE TITLE
Consider moving to libnpm

### ISSUE THREAD

**Issue by Nicholaiii** [anseki/process-bridge#1]
The npm programmatic API is [not supported](https://npm.community/t/how-do-i-use-npm-api-programatically/5207/2), it's supposed to be private and you're not suppsoed to use it, and the use of it in process-bridge breaks vscode-color for anyone [not using outdated npm versions](https://github.com/anseki/vscode-color/issues/108). 
It is not a [bug in npm](https://github.com/anseki/vscode-color/issues/108#issuecomment-774365209), because it's not a public API. 

Consider moving to the officially supported [libnpm](https://www.npmjs.com/package/libnpm), to maintain future _and current_ compatibility

**Comment by anseki** [comment]
Hi @Nicholaiii, thank you for the comment.
I think that vscode-color and this extension have already finished its part since VS Code supports internal Color Picker.
I will rethink that if more requests come.

**Comment by Nicholaiii** [comment]
Unfortunately the internal color picker only works in html and css files, and vscode's official response to this issue is using extensions, I reckon this is where vscode-color comes in handy :)

**Comment by anseki** [comment]
I know that the internal Color Picker is very simple.
Anyway, the extension has low demand now.

**Comment by anseki** [comment]
This issue is closed.
I still welcome comments.
